/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bharath' at '4/14/16 5:05 PM' with Gradle 2.0
 *
 * @author bharath, @date 4/14/16 5:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
